
# -*- coding: utf-8 -*-
"""AIML LAB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-bf3fGnhDLP2YYukNqJzDWSvTkrNC_HR

Date = 07/07/2025

NumPy Library
"""

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

import numpy as np
print(np.__version__)

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[0])

import numpy as np
arr =np.array([1,2,3,4,5])
print(arr[2] + arr[3])

import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print('2nd element on 1st row: ', arr[0,1])
print('5th element on 2nd row:',arr[1,4])

"""Array Slicing"""

import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[::-1])
print(arr[4:])
print(arr[:4])

import numpy as np
arr = np.array([1,2,3,4])
print(arr.dtype)

import numpy as np
arr = np.array(['apple','banana','cherry'])
print(arr.dtype)

"""DATA TYPES IN NUMPY

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type(void)
"""

#Make a copy, change the original array, and display both arrays

import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

# Make a view, change the original array, and display both arrays :
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

import numpy as np
arr = np.array([1,2,3,4],ndmin = 5)
print(arr)
print('shape of array:',arr.shape)

"""Date = 14/07/25"""

import numpy as np
a = np.array([(1,2,3),(3,4,4)])
print(a)
print(type(a))

b = np.array([1,2,3])
print(b)
print(b.dtype) #tells us the data types of the elements in an array
print(type(b))

print(a.ndim) #get dimensions(number dimension)
print(b.ndim)

print(a.shape)
print(b.shape)

a = np.array([(1,2,3),(3,4,4)], dtype = 'int16') #if we want to specify the size of it,we can while declaring the size integer type having size = 16
print(a.dtype)
print(a.itemsize)

a = np.array([(1,2,3),(3,4,4)],dtype = 'int32')
print(a.itemsize) #One element will have how many bytes 1byte = 8 bits
print(a.size) #Total number of elements in the array
print(a.shape) #Will  give Row,Column

print(a.size * a.itemsize) # another
print(a.nbytes) #total number of bytes in the array or total size

"""Accessing / Changing access"""

w = np.arange(start = 1, stop = 10, step = 2) #
print(w)

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)

print(a[1,4])
a[0,-1]

print(a[1, : ])
print(a[:,5])

print(a[0,1:6:2])

a[1,6] = 20 #directly change the element
print(a)

a[:,2] = 5 #All rows, with 3rd column changed to 5
print(a)

q = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
#3D : vector of Matrix #2d : Matrix # 1D : Vector
print(q)

print(q[0,1,1]) #1 Matrix, 2row, 2 column
print(q[:,1,:]) # All matrix, 2nd roow, all columns

q[:,1,:] = [9,9],[9,9] #Replacing All matrix, 2nd row, all column

q

"""Initializing DIfferent types of arrays"""

a = np.zeros((2,2)) #All 0s matrix, specify shape
print(a)

print(np.zeros((2,2,3)))

print(np.ones((4,2,2),dtype = 'int32')) #All 1s matrix

print(np.full((2,2),99,dtype = 'float32')) #Matrix with 2,2 size and is filled with 99 element with datatye float 32

print(np.full_like(q,7)) #reusing previous matrix (q) and filling it with 7

"""Creating random numbers"""

print(np.random.rand(2,3)) #create array of size 2,3 with random numbers between [0,1] 0(inclusive) and 1(exclusive)

print(np.random.random_sample(q.shape))

print(np.random.randint(7,size = (3,3))) #randint = integer and generate value between 0 (Include) and 7 (Exclude)

print(np.random.randint(-6,6,size = (2,2))) # between -6(Inclusive) and 6[excluded]

print(np.random.randint(-6,6,2)) #2 is the size, i.e, only two values between -6(Inclusive) and 6[excluded]

print(np.identity(7,dtype = 'int16')) #To create an identity matrix and 7 is the number of rows

arr = np.array([1,2,3])
z = np.repeat(arr,3,axis = 0)
print(z)

"""Date = 21/07/25

Copying Arrays
"""

a = np.array([1,2,3]) #a is created and then b is also pointing to same object, a copy is not getting created (it's the same objects)
b = a
print(b)
b
b[0] = 100
print(b)
print(a)

b = a.copy() #Here the contents of a is copied in b
print(a)
b[2] = 90
print(b)
print(a)

"""Mathematics/BroadCasting"""

a = np.array([1,2,3,4])
print(a)

a += 2
print(a)
print(a+2)
print(a - 2)
print(a * 2)
print(a/2)

b = np.array([1,0,1,0])
print(a+b)
print(a ** 2)

"""Linear Algebra"""

a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b) #Matrix multiplication : output would be 2 by2 matrix

c = np.identity(3)
np.linalg.det(c)

"""Statistics"""

stats = np.array([[5,2,3],[4,5,6]])
stats

print("Maximum :",np.max(stats, axis = 1)) #It returns the new array with max values from each row and axis = 1 means row

print("Minimum :",np.min(stats, axis = 0)) #It returns the new array with min values from each column and axis = 0 means column

print(np.min(stats))

print(np.sum(stats))

sum(sum(stats))

"""Date = 28/07/25

**Reorganizing Arrays**
"""

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(8,1) #Reshaping array as 8 rows and 1 column
print(after)

#Vertically Staking vectors

v1 = np.array([1,2,3,4]) #vector
v2 = np.array([5,6,7,8]) #vector

np.vstack([v1,v2,v2])  #stacking vectors together as matrices

#Horizontal Stacking

h1 = np.ones((1,2)) #matrix
h2 = np.zeros((1,2)) #matrix
print(h1)
print(h2)

np.hstack((h1,h2))

"""#PANDAS

* Pandas are more flexible and can work on big data '
* They are open source built on top of numPy lib
* It is
"""

from google.colab import files
uploaded = files.upload()   #1st way to load the data in pandas #2nd way via folder

import pandas as pd
df = pd.read_csv('pokemon_data.csv')
df

print(df.columns) #reading headers (column names)

print(df.head(3)) #reading starting 3 rows(By default : it gives 5 rows of starting)

print(df["Name"])

print(df["Name"][0:10]) #First 10 rows of the specific column using slicing

df.Name  #Simply the name of the column

print(df[["Name","Type 1","HP"]])

print(df.iloc[1])

print(df.iloc[2,1])

from google.colab import drive #3rd via uploading file into drive and then mounting the drive
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/AIML Lab/pokemon_data.csv'

import pandas as pd
df = pd.read_csv(file_path) #dataframe is the reference to the file

df

"""Reading Data in Pandas"""

#reading headers
print(df.columns)

print(df.head) #default

print(df.head(3)) #1st three rows of each column

print(df['Name'])

print(df['Name'][0:10]) #1st 10 names

df.Name  #simply the name of the column

print(df[["Name", "Type 1", "HP"]]) #print 3 column details

print(df.iloc[1])  #Read each row

print(df.shape) #Total number of (rows, column)

print(df.info)

print(df.describe())  #This provides all the stats like mean, standard deviation etc

df.sort_values("Name")

df.sort_values("Name",ascending = False)

print(df.sort_values(["Type 1","HP"],ascending = False))

print(df.sort_values(["Type 1","HP"],ascending = [1,0]))

"""Date = 18/08/25

Practical 3 EDA (EXPLORATORY DATA ANALYSIS) : To understand the data
"""

from google.colab import drive #EDA : Ex
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/AIML Lab/train.csv'

import pandas as pd
df = pd.read_csv(file_path)

"""Data Analysis means asking yourself the questions"""

#1. What is the size of data
df.shape

#2. How does the data looks like ?
df.head()

#3. What is the datatype of the columns ?
df.info()

#4.Are there any missing values?
df.isnull()

df.isnull().sum() #each attributes have this many NULL values

#5.Is there any duplicate values ?

df.duplicated().sum()

#6. Is there any corelation ?
df.corr(numeric_only = True) #Any attribute is connected with (or related to) another attribute

"""Date = 25/08/25"""

df.corr(numeric_only = True)['Survived']

df.corr(numeric_only = True)['Pclass']

df.corr(numeric_only = True)["Age"]

"""#SEABORN MODULE

It has inbuilt dataset
"""

import seaborn as sns

sns.catplot(df["Pclass"])

sns.catplot(df["Age"])

sns.catplot(df["Survived"])

sns.boxplot(df["Survived"])

sns.boxplot(df["Pclass"])

sns.boxplot(df['Age'])

sns.scatterplot(x="Survived",y="Pclass",data = df)

"""One-variate : A variable is realted to another one variable

It shows relationship between 2 variables

Date : 25/08/25

MultiVariate EDA

Multi-variate Data Analyis : As one variable may be related to more than one variable or attribute

It shows relationship between 2 or more variables
"""

import seaborn as sns #because seaborn has multiple visualisation and graphs like plots, etc ,matplot lib has all plots, graphs

df = sns.load_dataset('tips') #df = dataframe referring to tips dataset  and tips dataset is already available in seaborn library

titanic = pd.read_csv(file_path)

df.head()

sns.scatterplot(x = 'total_bill', y = 'tip', data = df)

sns.scatterplot(x='total_bill', y='tip', hue=df['sex'], data=df)  #hue is used to add a third dimension by color-coding the points based on a categorical values and any other keyword (like z) is not used or will give keyword erroe

sns.scatterplot(x='total_bill', y='tip', hue=df['sex'], style = df['smoker'], data=df) #style is a standard parameter is used to differentiate data points using marker shapes (like circles, triangles, squares)

sns.scatterplot(x='total_bill', y='tip', hue=df['sex'], style = df['smoker'], size = df["size"] ,data=df) #The size parameter is a standard parameter that maps a numeric or categorical variable to the size of the points (bubbles) in the scatter plot.

sns.barplot(x = "Pclass" , y = "Age", data = titanic)

sns.barplot(x = "Pclass" , y = "Age", hue = df["sex"],data = titanic)  #(Outliers : are not present)

"""Date = 1/09/2025"""

sns.boxplot(x = "Pclass" , y = "Age", hue = df['sex'], data = titanic) #Outliers are present (They are the values that are very different from our dataset)

sns.displot(titanic['Age']) #This is a way to get avergae values of particular categories (It is used to visualize the distribution of a particular dataset. )

pd.crosstab(titanic['Pclass'],titanic['Survived']) #crosstab : it gives ius the summarize of particular tabs and It helps to: i)Count frequencies between two categories ii)Analyze relationships between categorical variables iii)Create pivot-table-like summaries

sns.heatmap(pd.crosstab(titanic['Pclass'],titanic['Survived']))

pd.crosstab(titanic['SibSp'],titanic['Survived'])

"""Date = 08/09/25"""

sns.clustermap(pd.crosstab(titanic['SibSp'],titanic['Survived']))

df1 = sns.load_dataset("iris")

df1.head()

df1.shape

sns.pairplot(df1,hue="species")

df2 = sns.load_dataset("flights")

df2.head()

df2.shape

df2.info()

df2.groupby("year")["passengers"].sum()

sns.lineplot(x = "year", y = "passengers",data = df2)
